In [1]:
#data encoding >> convarting categorical column into numeric
#nominal/OHE
#label and oedinal encoding
#targer guided ordinal encoding

In [2]:
# nominal / one hote encoding >> binary vactor for each catagories

#example: single, married, separated

#single : [1, 0 ,0]
#married : [0, 1, 0]
#separated : [0, 0, 1]  

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import OneHotEncoder

In [4]:
df = pd.DataFrame({'status' : ['single', 'married', 'separated','single', 'married', 'separated','single', 'married', 'separated','single', 'married', 'separated','single', 'married', 'separated','single', 'married', 'separated','single', 'married', 'separated','single', 'married', 'separated','single', 'married', 'separated','single', 'married', 'separated']})

In [5]:
df

,status
0,single
1,married
2,separated
3,single
4,married
5,separated
6,single
7,married
8,separated
9,single


In [6]:
encoder = OneHotEncoder()

In [7]:
encoder

OneHotEncoder()

In [8]:
encoded = encoder.fit_transform(df[['status']]).toarray()

In [9]:
encoder.get_feature_names_out()

array(['status_married', 'status_separated', 'status_single'],
      dtype=object)

In [10]:
encoder_df = pd.DataFrame(encoded, columns= encoder.get_feature_names_out())

In [11]:
encoder_df

,status_married,status_separated,status_single
0,0.0,0.0,1.0
1,1.0,0.0,0.0
2,0.0,1.0,0.0
3,0.0,0.0,1.0
4,1.0,0.0,0.0
5,0.0,1.0,0.0
6,0.0,0.0,1.0
7,1.0,0.0,0.0
8,0.0,1.0,0.0
9,0.0,0.0,1.0


In [12]:
#new data 
encoder.transform([['single']]).toarray()

array([[0., 0., 1.]])

In [13]:
pd.concat([df,encoder_df],axis=1)

,status,status_married,status_separated,status_single
0,single,0.0,0.0,1.0
1,married,1.0,0.0,0.0
2,separated,0.0,1.0,0.0
3,single,0.0,0.0,1.0
4,married,1.0,0.0,0.0
5,separated,0.0,1.0,0.0
6,single,0.0,0.0,1.0
7,married,1.0,0.0,0.0
8,separated,0.0,1.0,0.0
9,single,0.0,0.0,1.0


In [14]:
df_dummies = pd.get_dummies(df, columns=['status'])

In [15]:
df_dummies

,status_married,status_separated,status_single
0,False,False,True
1,True,False,False
2,False,True,False
3,False,False,True
4,True,False,False
5,False,True,False
6,False,False,True
7,True,False,False
8,False,True,False
9,False,False,True


practice

In [16]:
df_tip = sns.load_dataset('tips')

In [17]:
df_tip

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [18]:
encoder = OneHotEncoder()

In [19]:
encoded = encoder.fit_transform(df_tip[['sex', 'time', 'day', 'smoker']]).toarray()

In [20]:
encoded

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 1.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]])

In [21]:
encoder.get_feature_names_out()

array(['sex_Female', 'sex_Male', 'time_Dinner', 'time_Lunch', 'day_Fri',
       'day_Sat', 'day_Sun', 'day_Thur', 'smoker_No', 'smoker_Yes'],
      dtype=object)

In [22]:
encoder_df = pd.DataFrame(encoded, columns= encoder.get_feature_names_out())

In [23]:
encoder_df

,sex_Female,sex_Male,time_Dinner,time_Lunch,day_Fri,day_Sat,day_Sun,day_Thur,smoker_No,smoker_Yes
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
239,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
240,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
241,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
242,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0


In [24]:
# label encoding >> assigns unique label to the categories

In [25]:
df

,status
0,single
1,married
2,separated
3,single
4,married
5,separated
6,single
7,married
8,separated
9,single


In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
label_encoder = LabelEncoder()

In [28]:
label_encoder.fit_transform(df[['status']])

array([2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1])

In [29]:
label_encoder.transform([['single']])

array([2])

In [30]:
label_encoder.transform([['separated']])

array([1])

In [31]:
# ordinal encoding

#high school: 1
#graduate: 2
#post graduate : 3
# phd : 4

In [32]:
from sklearn.preprocessing import OrdinalEncoder

In [37]:
df = pd.DataFrame({"qualification" : ["HS", "GR", "PG", "PHD","HS", "GR", "PG", "PHD"]})

In [38]:
df

,qualification
0,HS
1,GR
2,PG
3,PHD
4,HS
5,GR
6,PG
7,PHD


In [45]:
encoder = OrdinalEncoder(categories=[["HS", "GR", "PG", "PHD"]])

In [47]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [1.],
       [2.],
       [3.]])

In [49]:
#new data

encoder.transform([['PG']])

array([[2.]])

In [51]:
#TARGET GUIDED ORDINAL ENCODING
#relationship with garget variable
#a lot of unique catagories 
# replace the category with the mean and median of respective groupes target variable

In [57]:
df = pd.DataFrame({'time': ['lunch', 'breakfirst', 'dinner','lunch', 'breakfirst', 'dinner','lunch', 'breakfirst', 'dinner'],
                   'total_bill': [120, 130, 90, 125, 150, 190, 160, 198, 45]})

In [58]:
df

,time,total_bill
0,lunch,120
1,breakfirst,130
2,dinner,90
3,lunch,125
4,breakfirst,150
5,dinner,190
6,lunch,160
7,breakfirst,198
8,dinner,45


In [61]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [62]:
mean_price

{'breakfirst': 159.33333333333334,
 'dinner': 108.33333333333333,
 'lunch': 135.0}

In [63]:
df['time_encoded'] = df['time'].map(mean_price)

In [85]:
df


,time,total_bill,time_encoded
0,lunch,120,135.000000
1,breakfirst,130,159.333333
2,dinner,90,108.333333
3,lunch,125,135.000000
4,breakfirst,150,159.333333
5,dinner,190,108.333333
6,lunch,160,135.000000
7,breakfirst,198,159.333333
8,dinner,45,108.333333


homework

In [66]:
tip = sns.load_dataset('tips')

In [67]:
tip

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [69]:
dt_price = tip.groupby('day')['tip'].mean().to_dict()

In [89]:
tbd_price = tip.groupby('day')['total_bill'].mean().to_dict()

In [70]:
dt_price

{'Thur': 2.7714516129032254,
 'Fri': 2.734736842105263,
 'Sat': 2.993103448275862,
 'Sun': 3.2551315789473683}

In [90]:
tbd_price

{'Thur': 17.682741935483868,
 'Fri': 17.15157894736842,
 'Sat': 20.44137931034483,
 'Sun': 21.41}

In [87]:
tip['day_tip'] = tip['day'].map(dt_price)

In [91]:
tip['total_bill_day'] = tip['day'].map(tbd_price)

In [92]:
tip

,total_bill,tip,sex,smoker,day,time,size,day_tip,total_bill_day
0,16.99,1.01,Female,No,Sun,Dinner,2,3.255132,21.410000
1,10.34,1.66,Male,No,Sun,Dinner,3,3.255132,21.410000
2,21.01,3.50,Male,No,Sun,Dinner,3,3.255132,21.410000
3,23.68,3.31,Male,No,Sun,Dinner,2,3.255132,21.410000
4,24.59,3.61,Female,No,Sun,Dinner,4,3.255132,21.410000
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,2.993103,20.441379
240,27.18,2.00,Female,Yes,Sat,Dinner,2,2.993103,20.441379
241,22.67,2.00,Male,Yes,Sat,Dinner,2,2.993103,20.441379
242,17.82,1.75,Male,No,Sat,Dinner,2,2.993103,20.441379
